/**
 * Candidate companies for Discovery V2 seed.
 * Run: pnpm build:seed && pnpm verify:boards --write
 */
export type SeedCandidate = {
  id: string;
  companyName: string;
  atsProvider: "greenhouse" | "lever" | "ashby";
  boardSlug: string;
  country: "CA" | "US" | "GLOBAL";
  tags: string[];
  companyWebsite?: string;
};

function gh(slug: string, name: string, country: SeedCandidate["country"], tags: string[]): SeedCandidate {
  return { id: slug, companyName: name, atsProvider: "greenhouse", boardSlug: slug, country, tags };
}
function lever(slug: string, name: string, country: SeedCandidate["country"], tags: string[]): SeedCandidate {
  return { id: slug, companyName: name, atsProvider: "lever", boardSlug: slug, country, tags };
}
function ashby(slug: string, name: string, country: SeedCandidate["country"], tags: string[]): SeedCandidate {
  return { id: slug, companyName: name, atsProvider: "ashby", boardSlug: slug, country, tags };
}

const baseTags: string[] = [];

export const SEED_CANDIDATES: SeedCandidate[] = [
  // Canada-focused
  gh("shopify", "Shopify", "CA", [...baseTags, "fintech", "ecommerce"]),
  lever("wealthsimple", "Wealthsimple", "CA", [...baseTags, "fintech"]),
  lever("clio", "Clio", "CA", [...baseTags, "legal-tech"]),
  gh("hootsuite", "Hootsuite", "CA", [...baseTags, "saas"]),
  gh("applyboard", "ApplyBoard", "CA", [...baseTags, "edtech"]),
  lever("dialogue", "Dialogue", "CA", [...baseTags, "healthtech"]),
  gh("ada", "Ada", "CA", [...baseTags, "ai", "saas"]),
  ashby("jobber", "Jobber", "CA", [...baseTags, "saas"]),
  ashby("1password", "1Password", "CA", [...baseTags, "security"]),
  ashby("benchsci", "BenchSci", "CA", [...baseTags, "ai"]),
  ashby("koho", "KOHO", "CA", [...baseTags, "fintech"]),
  ashby("fullscript", "Fullscript", "CA", [...baseTags, "healthtech"]),
  ashby("clio", "Clio", "CA", [...baseTags, "legal-tech"]),
  gh("ecobee", "ecobee", "CA", [...baseTags, "iot"]),
  lever("later", "Later", "CA", [...baseTags, "saas"]),
  gh("freshbooks", "FreshBooks", "CA", [...baseTags, "fintech"]),
  ashby("vendasta", "Vendasta", "CA", [...baseTags, "saas"]),
  ashby("dapper", "Dapper Labs", "CA", [...baseTags, "web3"]),
  ashby("hopper", "Hopper", "CA", [...baseTags, "travel-tech"]),
  ashby("clearco", "Clearco", "CA", [...baseTags, "fintech"]),

  // Global / US remote-friendly (Greenhouse)
  gh("stripe", "Stripe", "GLOBAL", [...baseTags, "fintech"]),
  gh("figma", "Figma", "GLOBAL", [...baseTags, "design-tools"]),
  gh("discord", "Discord", "GLOBAL", [...baseTags, "consumer"]),
  gh("airtable", "Airtable", "GLOBAL", [...baseTags, "saas"]),
  gh("duolingo", "Duolingo", "GLOBAL", [...baseTags, "edtech"]),
  gh("hubspot", "HubSpot", "GLOBAL", [...baseTags, "saas"]),
  gh("anthropic", "Anthropic", "GLOBAL", [...baseTags, "ai"]),
  gh("coinbase", "Coinbase", "GLOBAL", [...baseTags, "fintech", "crypto"]),
  gh("databricks", "Databricks", "US", [...baseTags, "data"]),
  gh("reddit", "Reddit", "GLOBAL", [...baseTags, "consumer"]),
  gh("plaid", "Plaid", "US", [...baseTags, "fintech"]),
  gh("brex", "Brex", "US", [...baseTags, "fintech"]),
  gh("scaleai", "Scale AI", "US", [...baseTags, "ai"]),
  gh("rippling", "Rippling", "US", [...baseTags, "saas"]),
  gh("chime", "Chime", "US", [...baseTags, "fintech"]),
  gh("lyft", "Lyft", "US", [...baseTags, "mobility"]),
  gh("pinterest", "Pinterest", "US", [...baseTags, "consumer"]),
  gh("asana", "Asana", "GLOBAL", [...baseTags, "saas"]),
  gh("dropbox", "Dropbox", "GLOBAL", [...baseTags, "saas"]),
  gh("gitlab", "GitLab", "GLOBAL", [...baseTags, "devtools"]),
  gh("mongodb", "MongoDB", "GLOBAL", [...baseTags, "data"]),
  gh("twilio", "Twilio", "GLOBAL", [...baseTags, "saas"]),
  gh("zapier", "Zapier", "GLOBAL", [...baseTags, "saas"]),
  gh("webflow", "Webflow", "GLOBAL", [...baseTags, "frontend-heavy"]),
  gh("retool", "Retool", "GLOBAL", [...baseTags, "devtools"]),
  gh("instacart", "Instacart", "US", [...baseTags, "consumer"]),
  gh("robinhood", "Robinhood", "US", [...baseTags, "fintech"]),
  gh("affirm", "Affirm", "US", [...baseTags, "fintech"]),
  gh("benchling", "Benchling", "US", [...baseTags, "biotech"]),
  gh("contentful", "Contentful", "GLOBAL", [...baseTags, "saas"]),
  gh("amplitude", "Amplitude", "GLOBAL", [...baseTags, "saas"]),
  gh("sentry", "Sentry", "GLOBAL", [...baseTags, "devtools"]),
  gh("cloudflare", "Cloudflare", "GLOBAL", [...baseTags, "infra"]),
  gh("gusto", "Gusto", "US", [...baseTags, "saas"]),
  gh("rubrik", "Rubrik", "US", [...baseTags, "security"]),
  gh("snap", "Snap", "US", [...baseTags, "consumer"]),
  gh("block", "Block", "US", [...baseTags, "fintech"]),
  gh("okta", "Okta", "GLOBAL", [...baseTags, "security"]),
  gh("hashicorp", "HashiCorp", "GLOBAL", [...baseTags, "devtools"]),
  gh("elastic", "Elastic", "GLOBAL", [...baseTags, "data"]),
  gh("datadog", "Datadog", "GLOBAL", [...baseTags, "devtools"]),
  gh("pagerduty", "PagerDuty", "GLOBAL", [...baseTags, "saas"]),
  gh("fastly", "Fastly", "GLOBAL", [...baseTags, "infra"]),
  gh("cockroachlabs", "Cockroach Labs", "US", [...baseTags, "data"]),
  gh("vercel", "Vercel", "GLOBAL", [...baseTags, "frontend-heavy"]),
  gh("notion", "Notion", "GLOBAL", [...baseTags, "saas"]),
  gh("figma", "Figma", "GLOBAL", [...baseTags, "design-tools"]),
  gh("grammarly", "Grammarly", "GLOBAL", [...baseTags, "ai"]),
  gh("coursera", "Coursera", "GLOBAL", [...baseTags, "edtech"]),
  gh("doordash", "DoorDash", "US", [...baseTags, "consumer"]),
  gh("sofi", "SoFi", "US", [...baseTags, "fintech"]),
  gh("checkr", "Checkr", "US", [...baseTags, "saas"]),
  gh("flexport", "Flexport", "US", [...baseTags, "logistics"]),
  gh("ginkgo", "Ginkgo Bioworks", "US", [...baseTags, "biotech"]),
  gh("navan", "Navan", "GLOBAL", [...baseTags, "travel-tech"]),
  gh("dbtlabs", "dbt Labs", "GLOBAL", [...baseTags, "data"]),
  gh("launchdarkly", "LaunchDarkly", "GLOBAL", [...baseTags, "devtools"]),
  gh("mixpanel", "Mixpanel", "GLOBAL", [...baseTags, "saas"]),
  gh("segment", "Segment", "GLOBAL", [...baseTags, "saas"]),
  gh("netlify", "Netlify", "GLOBAL", [...baseTags, "frontend-heavy"]),
  gh("circleci", "CircleCI", "GLOBAL", [...baseTags, "devtools"]),
  gh("calendly", "Calendly", "GLOBAL", [...baseTags, "saas"]),
  gh("miro", "Miro", "GLOBAL", [...baseTags, "saas"]),
  gh("canva", "Canva", "GLOBAL", [...baseTags, "design-tools"]),
  gh("airbnb", "Airbnb", "GLOBAL", [...baseTags, "travel-tech"]),
  gh("spotify", "Spotify", "GLOBAL", [...baseTags, "consumer"]),
  gh("squarespace", "Squarespace", "GLOBAL", [...baseTags, "saas"]),
  gh("wayfair", "Wayfair", "US", [...baseTags, "ecommerce"]),
  gh("waymo", "Waymo", "US", [...baseTags, "ai"]),
  gh("anduril", "Anduril", "US", [...baseTags, "defense"]),
  gh("openai", "OpenAI", "US", [...baseTags, "ai"]),
  gh("figma", "Figma", "GLOBAL", [...baseTags, "design-tools"]),

  // Lever boards
  lever("netflix", "Netflix", "GLOBAL", [...baseTags, "consumer"]),
  lever("spotify", "Spotify", "GLOBAL", [...baseTags, "consumer"]),
  lever("palantir", "Palantir", "US", [...baseTags, "data"]),
  lever("atlassian", "Atlassian", "GLOBAL", [...baseTags, "saas"]),
  lever("box", "Box", "GLOBAL", [...baseTags, "saas"]),
  lever("cruise", "Cruise", "US", [...baseTags, "ai"]),
  lever("flexport", "Flexport", "US", [...baseTags, "logistics"]),
  lever("reddit", "Reddit", "GLOBAL", [...baseTags, "consumer"]),
  lever("lyft", "Lyft", "US", [...baseTags, "mobility"]),
  lever("square", "Square", "US", [...baseTags, "fintech"]),
  lever("robinhood", "Robinhood", "US", [...baseTags, "fintech"]),
  lever("affirm", "Affirm", "US", [...baseTags, "fintech"]),
  lever("plaid", "Plaid", "US", [...baseTags, "fintech"]),
  lever("gusto", "Gusto", "US", [...baseTags, "saas"]),
  lever("checkr", "Checkr", "US", [...baseTags, "saas"]),
  lever("segment", "Segment", "GLOBAL", [...baseTags, "saas"]),
  lever("mixpanel", "Mixpanel", "GLOBAL", [...baseTags, "saas"]),
  lever("benchling", "Benchling", "US", [...baseTags, "biotech"]),
  lever("carta", "Carta", "US", [...baseTags, "fintech"]),
  lever("figma", "Figma", "GLOBAL", [...baseTags, "design-tools"]),
  lever("notion", "Notion", "GLOBAL", [...baseTags, "saas"]),
  lever("ramp", "Ramp", "US", [...baseTags, "fintech"]),
  lever("mercury", "Mercury", "US", [...baseTags, "fintech"]),
  lever("rippling", "Rippling", "US", [...baseTags, "saas"]),
  lever("deel", "Deel", "GLOBAL", [...baseTags, "saas"]),
  lever("remote", "Remote", "GLOBAL", [...baseTags, "saas"]),
  lever("gitlab", "GitLab", "GLOBAL", [...baseTags, "devtools"]),

  // Ashby boards
  ashby("notion", "Notion", "GLOBAL", [...baseTags, "saas"]),
  ashby("linear", "Linear", "GLOBAL", [...baseTags, "devtools"]),
  ashby("vercel", "Vercel", "GLOBAL", [...baseTags, "frontend-heavy"]),
  ashby("ramp", "Ramp", "US", [...baseTags, "fintech"]),
  ashby("mercury", "Mercury", "US", [...baseTags, "fintech"]),
  ashby("deel", "Deel", "GLOBAL", [...baseTags, "saas"]),
  ashby("openai", "OpenAI", "US", [...baseTags, "ai"]),
  ashby("anthropic", "Anthropic", "GLOBAL", [...baseTags, "ai"]),
  ashby("figma", "Figma", "GLOBAL", [...baseTags, "design-tools"]),
  ashby("retool", "Retool", "GLOBAL", [...baseTags, "devtools"]),
  ashby("vanta", "Vanta", "US", [...baseTags, "security"]),
  ashby("rippling", "Rippling", "US", [...baseTags, "saas"]),
  ashby("carta", "Carta", "US", [...baseTags, "fintech"]),
  ashby("anduril", "Anduril", "US", [...baseTags, "defense"]),
  ashby("perplexity", "Perplexity", "US", [...baseTags, "ai"]),
  ashby("harvey", "Harvey", "US", [...baseTags, "legal-tech", "ai"]),
  ashby("glean", "Glean", "US", [...baseTags, "ai"]),
  ashby("sierra", "Sierra", "US", [...baseTags, "ai"]),
  ashby("cognition", "Cognition", "US", [...baseTags, "ai"]),
  ashby("elevenlabs", "ElevenLabs", "GLOBAL", [...baseTags, "ai"]),
  ashby("runway", "Runway", "US", [...baseTags, "ai"]),
  ashby("replit", "Replit", "GLOBAL", [...baseTags, "devtools"]),
  ashby("cursor", "Cursor", "GLOBAL", [...baseTags, "devtools", "ai"]),
  ashby("lovable", "Lovable", "GLOBAL", [...baseTags, "ai"]),
  ashby("supabase", "Supabase", "GLOBAL", [...baseTags, "devtools"]),
  ashby("neon", "Neon", "GLOBAL", [...baseTags, "data"]),
  ashby("clerk", "Clerk", "GLOBAL", [...baseTags, "devtools"]),
  ashby("resend", "Resend", "GLOBAL", [...baseTags, "devtools"]),
  ashby("cal", "Cal.com", "GLOBAL", [...baseTags, "saas"]),
  ashby("posthog", "PostHog", "GLOBAL", [...baseTags, "saas"]),
  ashby("incident", "Incident.io", "GLOBAL", [...baseTags, "saas"]),
  ashby("plain", "Plain", "GLOBAL", [...baseTags, "saas"]),
  ashby("attio", "Attio", "GLOBAL", [...baseTags, "saas"]),
  ashby("modal", "Modal", "US", [...baseTags, "ai", "infra"]),
  ashby("wandb", "Weights & Biases", "GLOBAL", [...baseTags, "ai"]),
  ashby("langchain", "LangChain", "US", [...baseTags, "ai"]),
  ashby("cohere", "Cohere", "CA", [...baseTags, "ai"]),
  ashby("shopify", "Shopify", "CA", [...baseTags, "ecommerce"]),
  ashby("wealthsimple", "Wealthsimple", "CA", [...baseTags, "fintech"]),
];
